### ISSUE TITLE
Transfer Ownership Tasks

### ISSUE THREAD

**Issue by redonkulus** [pure-css/pure#691]
### Description

This is a running task of the items needed to complete the transfer from the Yahoo org to the Pure-CSS org.

### Tasks

1. [x] Move all pure repos to the pure-css org I created. 
2. [x] Add @KeiroD and anyone else that wants to maintain the project. Invite sent out.
3. [x] **[In progress]** Update all code references from `yahoo/pure*` to `pure-css/*`. Repos:
   - [x] pure - https://github.com/pure-css/pure/commit/de4c3136cc6a5caca13d75ab3740f73a78592711
   - [x] pure-site - https://github.com/pure-css/pure-site/commit/496b09b6279be1c6b79e866d2ca1286addd3b5eb
4. [x] Document release process - https://github.com/pure-css/pure/wiki/Release-Process

### Post Transfer Work

I created a separate [issue](https://github.com/pure-css/pure/issues/692) for potential improvements to Pure's build/infrastructure.

**Comment by redonkulus** [comment]
This is work is now done. If anyone would like to help maintain this project, I can provide access. Thanks!

**Comment by redonkulus** [comment]
One last thing I should mention is that I setup the pure-site repository to auto deploy to Now.sh whenever a merge to master is completed. This way Yahoo/Oath can continue to pay/own the domain and hosting services until the community wants to take that over.
