### ISSUE TITLE
feat(site): build new documentation site

### ISSUE THREAD

**Issue by redonkulus** [pure-css/pure#787]
### Goals
- The goal is to rebuild the Purecss.io site on Docusaurus with as little changes as possible.
- Migrate off Zeit as v1 is EOL this summer. Purecss.io doesn't work on Zeit v2.

### Background
This PR adds a new documentation site for Pure with [Docusaurus](https://v2.docusaurus.io/). The [existing site](https://github.com/pure-css/pure-site) is built on old versions of Express, Handlebars, Broccoli and other custom libraries that are no longer supported. I've tried to upgrade the code, but there is so much to untangle that it's easier to build an entirely new site using newer technologies.

When looking to build a new site, I wanted something that did not require a server. This would help reduce server cost and maintenance. The current site is hosted on [Zeit](https://zeit.co/home) and cannot be upgraded to Zeit v2 without refactoring the code to work with newer versions of Nodejs. Furthermore, Pure is built for browsers and lends itself to work with static site generators very well.

I checked out a few different options (Jekyll ~ didn't want to build it in markdown, Gatsby ~ promising but complex), but settled on Docusaurus for its ease of use, readability and my own familiarity with React. React is probably a bit over engineered for a simple static site, but it's a nice language to work in, even if it's just a static site. Plus, at build time we can generate a fully static site and remove React entirely if need be.

### Deployment
My plan is to deploy the static site to Github Pages and serve it from there. Nothing better than free!

### Development
The site will exist within this repository and be developed against the latest version of Pure that is checked into the repository. Because the site is co-located with the Pure codebase, it will be easier to develop, test and deploy the site all at once time. The existing pure-site repository will be archived once the migration is complete.

### TODO
This will be a running list of things to complete before it is ready for production:

- [x] Migrate existing pages
- [x] Migrate examples
- [x] Deploy to GitHub Pages
- [x] Update purecss.io to point to <s>GitHub Pages</s> Zeit for now.

Please let me know if there are any other questions or concerns.

**Comment by redonkulus** [comment]
The new doc site is now served from the `site/` directory.
